Add continuous integration
akeneo/api-php-client-ee pull request #26
Opened 2018-01-12 13:47 UTC by damien-carcel

2018-01-12 17:04 UTC, ClementGautier requested changes

2018-01-12 17:04 UTC, ClementGautier commented on .ci/Jenkinsfile
> +            nfsVolume(mountPath: '/shared', serverAddress: "${env.NFS_IP}", serverPath: '/exports', readOnly: false),
nop

2018-01-12 17:04 UTC, ClementGautier commented on .ci/Jenkinsfile
> +        containerTemplate(name: "gcloud", ttyEnabled: true, command: 'cat', image: "eu.gcr.io/akeneo-ci/gcloud:1.0.17", resourceRequestCpu: '100m', resourceRequestMemory: '200Mi', envVars: [envVar(ke
1.0 + alwaysPullImage: true

2018-01-12 17:04 UTC, ClementGautier commented on .ci/Jenkinsfile
> +                    envVar(key: "COMPOSER_HOME", value: "/shared/.composer"),
to be removed

2018-01-15 15:28 UTC, ClementGautier approved these changes

2018-01-16 16:32 UTC, LaurentPetard approved these changes

2018-01-17 09:53 UTC, merged