API-423: Add submit proposal
akeneo/api-php-client-ee pull request #7
Opened 2017-11-23 09:49 UTC by damien-carcel

2017-11-23 14:38 UTC, ahocquard approved these changes

2017-11-24 10:53 UTC, LaurentPetard approved these changes

2017-11-24 13:59 UTC, ahocquard requested changes
Sorry for changing my mind about it: 
please implement it with a function named`submitForApproval` in the draft API.

It is better (Nolwenn think the same).

2017-11-27 09:20 UTC, ahocquard approved these changes

2017-11-27 09:49 UTC, merged