SDS-14449: Fixed access to headers' variable with wrong key
akeneo/api-php-client-ee pull request #95
Opened 2020-07-16 16:04 UTC by GiulianoDiVita

2020-07-16 16:41 UTC, mmetayer requested changes

2020-07-16 16:41 UTC, mmetayer commented on src/Api/AssetManager/AssetMediaFileApi.php
> -        if (!isset($headers['Asset-media-file-code'][0])) {
Actually HTTP headers are case insensitive according to [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2). We cannot guarantee that this case will be respected (the server can respond with either of `Asset-Media-File-Code`. `asset-media-file-code`, `Asset-media-file-code` header)

2020-07-16 16:42 UTC, mmetayer commented
Hey @GiulianoDiVita, I was about to submit a PR myself when I saw yours. As I explained in my review, I don't think your solution is correct, a better solution would be IMO:
```php
    private function extractCodeFromCreationResponse(ResponseInterface $response): string
    {
        $header = $response->getHeader('Asset-media-file-code'); // this method is case-insensitive, and returns an empty array if the header is not set

        if (empty($header)) {
            throw new RuntimeException('The response does not contain the code of the created media-file.');
        }

        return (string) $header[0];
    }
```

Would youlike me to submit a PR or would you rather fix yours?

2020-07-16 17:14 UTC, GiulianoDiVita commented
> Hey @GiulianoDiVita, I was about to submit a PR myself when I saw yours. As I explained in my review, I don't think your solution is correct, a better solution would be IMO:
> 
> ```
>     private function extractCodeFromCreationResponse(ResponseInterface $response): string
>     {
>         $header = $response->getHeader('Asset-media-file-code'); // this method is case-insensitive, and returns an empty array if the header is not set
> 
>         if (empty($header)) {
>             throw new RuntimeException('The response does not contain the code of the created media-file.');
>         }
> 
>         return (string) $header[0];
>     }
> ```
> 
> Would youlike me to submit a PR or would you rather fix yours?

Hi @mmetayer,

I modified the code following your review, hope now is ok.

Thank you,
Giuliano

2020-07-16 17:56 UTC, mmetayer commented
Nice!

I took the liberty of adding some tests and rebasing on master, I hope you don't mind :slightly_smiling_face:

2020-07-16 17:56 UTC, mmetayer approved these changes

2020-07-17 10:54 UTC, justasbieliauskas commented
Wait, I'm sorry, how does this solve the problem if a header is `Asset-media-file-code` (like in [documentation](https://api.akeneo.com/api-reference.html#post_asset_media_files)) or `Asset-Media-File-Code` (like in this [issue](#93))?

2020-07-17 12:20 UTC, mmetayer commented
@justasbieliauskas the HTTP header keys are case-insensitive (see [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)). Theoretically the HTTP server can include the header with any case
The issue was that we tested its existence with PHP's native `isset` function (which _is_ case sensitive).
By using the MessageInterface::getHeader() message, we ensure getting the correct header, regardless of its case (see PHPDoc [here](https://github.com/php-fig/http-message/blob/efd67d1dc14a7ef4fc4e518e7dee91c271d524e4/src/MessageInterface.php#L94))
To sum up, ```$response->getHeader('Asset-media-file-code')``` will return any of the following headers:
- Asset-media-file-code
- Asset-Media-File-Code
- asset-media-file-code
- ...

2020-07-17 12:27 UTC, SamirBoulil commented on src/Api/AssetManager/AssetMediaFileApi.php
> +        $header = $response->getHeader('asset-media-file-code');
```suggestion
        $assetMediaFileCode = $response->getHeader('asset-media-file-code');
```

2020-07-17 12:34 UTC, SamirBoulil approved these changes

2020-07-17 12:43 UTC, merged